language: python
python:
  - "3.8"

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose up --build -d cassandra-db; python run.py; docker-compose build
  - export JOB_NAME="read_spark_config.py"; docker-compose run py-spark
  - export JOB_NAME="example_job.py"; docker-compose run py-spark

notifications:
  email:
    on_error: never
    on_failure: never
    on_start: never
    on_cancel: never