version: '3'

services:
  cassandra-db:
    image: cassandra:3.0
    container_name: cassandra-db
    hostname: cassandra-db
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"

  spark-master:
    image: bde2020/spark-master:2.4.5-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - ENABLE_INIT_DAEMON=false

  spark-worker-1:
    image: bde2020/spark-worker:2.4.5-hadoop2.7
    container_name: spark-worker-1
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"

  py-spark:
    build: .
    environment:
      - ENABLE_INIT_DAEMON=false
      - "SPARK_MASTER=spark://spark-master:7077"
      - CASSANDRA_HOST=cassandra-db
      - SPARK_APPLICATION_PYTHON_LOCATION=/app/python_connector/pyspark_jobs/${JOB_NAME}





